### ISSUE TITLE
The task that is created does not work

### ISSUE THREAD

**Issue by johnths2** [vilmire/PBO2_Helper#1]
I used PBO2_helper on my Win 11 PC and everything looks good and the task was made.
The task however runs after restart, but the values where not injected.
After a restart of my PC the 8 values are still zero and not -30.

Again I have to manualy input the -30 values with PBO2 Tuner to let my core temps drop down during a stress test.
Also when i started PBO2 Tuner to do that the displayed values where zero.

**Comment by vilmire** [comment]
Can i see scheduler setting? Using V1.0.1?

**Comment by johnths2** [comment]
Good morning from my side,

I have the Dutch Version of Win 11

Win 11 - Taakplanner
Microsoft Corporation (c)
Versie: 1.0

The Task is made oké with PBO2 Helper and it also runs.
This runs >> C:\Program Files\PBO2 Helper\Debug\PBO2tuner.exe -30 -30 -30 -30 -30 -30 -30 -30
The problem however is that the  -30 values are not injected by PBO2tuner.exe

**Comment by vilmire** [comment]
https://github.com/PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner/blob/main/README.md

Can you check this article and what is diffrent your scheduler setting?

**Comment by johnths2** [comment]
Nothing at all, there is no difference!

I did it manual according to the article and after that with your PBO Helper both has the same result.
The problem is that the -30 values are not injected by the PBOtuner.exe when using a task.
The only solution for me at this moment, is to put the values in manually every time i startup the PC.

I hope it will be possible to put the values in the PBOtuner config file other then using a task.

**Comment by vilmire** [comment]
I also think it's good to have options in the config. If the result is the same even if you register manually, the scheduler helper doesn't seem to help. The issue will be closed.
