### ISSUE TITLE
Other values

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [vilmire/PBO2_Helper#2]
Firstly, thanks for the little tool. Works better for me than setting it manualy - that sometimes just doesn't apply after I boot up Windows for whatever reason.

Now a question: What would have to change, if I'd not only want to apply a curve-offset, but allso different values for PPT, TDC, and EDC?

**Comment by vilmire** [comment]
At the time of production, there was no such option, so I did not include it. I'll add it in the next update.

**Comment by TommvinHuwaltzky** [comment]
Hey, thanks for your answer.
But unfortunately, lowering PPT on my 5800X3D doesn't seem to do anything.
As far as I can tell, only Ryzen 7000 benefits from it.
But maybe for other people? I mean I seem to have won the silicon-lottery, since using an all-core-offset of -30 on my 5800X3D is completely-stable, but who knows?

**Comment by vilmire** [comment]
Done. I haven't checked advanced features work. I just only checked that the parameters are normally registered in the scheduler.
